# name of the Docker image, the Docker executor uses to run CI/CD jobs
image: ubuntu:latest

# Stages, which define when to run the jobs. For example, stages that run tests after stages that compile the code.
stages:
  - Build
  - Test
  - Deploy

# build job in Build stage
build:
  image: openjdk:17-alpine
  stage: Build
  script:
    - ./gradlew bootJar
  # The paths keyword determines which files to add to the job artifacts. All paths to files and directories are relative to the repository where the job was created.
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

# test job in Test stage
test:
  image: openjdk:17-alpine
  stage: Test
  needs:
    - build
  script:
    - ./gradlew check

# deploy job in Deploy stage
deploy:
  stage: Deploy
  needs:
    - test
  script:
    - ./scripts/deploy.sh