runtime: java17

handlers:
  - url: /.*
    script: this field is required, but ignored

env_variables:
  SPRING_PROFILES_ACTIVE: dev
  PORT: 8080
  SPRING_DATASOURCE_URL: jdbc:h2:mem:devdb
  SPRING_DATASOURCE_USERNAME: sa
  SPRING_DATASOURCE_PASSWORD:
