-- -- MUNICIPALITY
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Aartselaar');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Antwerpen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Arendonk');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Baarle-Hertog');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Balen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Beerse');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Berlaar');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Boechout');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Bonheiden');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Boom');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Bornem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Borsbeek');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Brasschaat');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Brecht');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Dessel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Duffel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Edegem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Essen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Geel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Grobbendonk');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Heist-op-den-Berg');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Hemiksem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Herentals');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Herenthout');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Herselt');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Hoogstraten');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Hove');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Hulshout');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kalmthout');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kapellen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kasterlee');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kontich');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Laakdal');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lier');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lille');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lint');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Malle');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Mechelen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Meerhout');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Merksplas');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Mol');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Mortsel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Niel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Nijlen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Olen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Oud-Turnhout');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Putte');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Puurs-Sint-Amands');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Ranst');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Ravels');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Retie');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Rijkevorsel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Rumst');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Schelle');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Schilde');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Schoten');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Sint-Katelijne-Waver');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Stabroek');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Turnhout');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Vorselaar');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Vosselaar');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Westerlo');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Wijnegem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Willebroek');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Wommelgem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Wuustwezel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zandhoven');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zoersel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zwijndrecht');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Aalst');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Aalter');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Assenede');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Berlare');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Beveren');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Brakel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Buggenhout');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Deinze');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Denderleeuw');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Dendermonde');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('De Pinte');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Destelbergen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Eeklo');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Erpe-Mere');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Evergem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Gavere');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Geraardsbergen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Ghent');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Haaltert');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Hamme');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Herzele');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Horebeke');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kaprijke');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kluisbergen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kruibeke');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kruisem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Laarne');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lebbeke');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lede');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lierde');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lievegem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lochristi');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lokeren');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Maarkedal');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Maldegem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Melle');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Merelbeke');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Moerbeke');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Nazareth');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Ninove');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Oosterzele');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Oudenaarde');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Ronse');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Sint-Gillis-Waas');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Sint-Laureins');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Sint-Lievens-Houtem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Sint-Martens-Latem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Sint-Niklaas');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Stekene');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Temse');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Waasmunster');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Wachtebeke');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Wetteren');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Wichelen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Wortegem-Petegem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zele');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zelzate');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zottegem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zulte');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zwalm');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Aarschot');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Affligem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Asse');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Beersel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Begijnendijk');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Bekkevoort');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Bertem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Bever');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Bierbeek');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Boortmeerbeek');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Boutersem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Diest');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Dilbeek');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Drogenbos');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Galmaarden');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Geetbets');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Glabbeek');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Gooik');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Grimbergen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Haacht');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Halle');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Herent');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Herne');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Hoegaarden');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Hoeilaart');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Holsbeek');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Huldenberg');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kampenhout');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kapelle-op-den-Bos');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Keerbergen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kortenaken');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kortenberg');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kraainem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Landen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lennik');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Leuven');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Liedekerke');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Linkebeek');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Linter');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Londerzeel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lubbeek');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Machelen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Meise');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Merchtem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Opwijk');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Oud-Heverlee');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Overijse');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Pepingen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Roosdaal');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Rotselaar');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Scherpenheuvel-Zichem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Sint-Genesius-Rode');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Sint-Pieters-Leeuw');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Steenokkerzeel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Ternat');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Tervuren');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Tielt-Winge');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Tienen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Tremelo');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Vilvoorde');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Wemmel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Wezembeek-Oppem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zaventem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zemst');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zoutleeuw');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Alken');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('As');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Beringen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Bilzen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Bocholt');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Borgloon');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Bree');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Diepenbeek');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Dilsen-Stokkem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Genk');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Gingelom');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Halen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Ham');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Hamont-Achel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Hasselt');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Hechtel-Eksel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Heers');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Herk-de-Stad');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Herstappe');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Heusden-Zolder');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Hoeselt');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Houthalen-Helchteren');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kinrooi');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kortessem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lanaken');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Leopoldsburg');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lommel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lummen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Maaseik');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Maasmechelen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Nieuwerkerken');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Oudsbergen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Peer');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Pelt');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Riemst');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Sint-Truiden');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Tessenderlo');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Tongeren');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Voeren');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Wellen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zonhoven');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zutendaal');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Alveringem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Anzegem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Ardooie');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Avelgem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Beernem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Blankenberge');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Bredene');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Bruges');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Damme');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Deerlijk');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('De Haan');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Dentergem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('De Panne');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Diksmuide');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Gistel');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Harelbeke');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Heuvelland');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Hooglede');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Houthulst');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Ichtegem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Ingelmunster');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Izegem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Jabbeke');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Knokke-Heist');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Koekelare');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Koksijde');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kortemark');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kortrijk');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Kuurne');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Langemark-Poelkapelle');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Ledegem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lendelede');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lichtervelde');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Lo-Reninge');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Menen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Mesen');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Meulebeke');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Middelkerke');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Moorslede');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Nieuwpoort');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Oostkamp');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Oostrozebeke');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Ostend');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Oudenburg');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Pittem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Poperinge');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Roeselare');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Ruiselede');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Spiere-Helkijn');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Staden');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Tielt');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Torhout');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Veurne');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Vleteren');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Waregem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Wervik');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Wevelgem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Wielsbeke');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Wingene');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Ypres');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zedelgem');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zonnebeke');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zuienkerke');
INSERT INTO MUNICIPALITY (NAME)
VALUES ('Zwevegem');

INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (1, 2630);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (2, 2000);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (2, 2018);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (2, 2020);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (2, 2030);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (2, 2040);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (2, 2050);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (2, 2060);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (3, 2370);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (4, 2387);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (5, 2490);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (6, 2340);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (7, 2590);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (8, 2530);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (9, 2820);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (10, 2850);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (11, 2880);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (12, 2150);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (13, 2930);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (14, 2960);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (15, 2480);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (16, 2570);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (17, 2650);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (18, 2910);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (19, 2440);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (20, 2280);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (21, 2220);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (22, 2620);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (23, 2200);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (24, 2270);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (25, 2230);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (26, 2320);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (27, 2540);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (28, 2235);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (29, 2920);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (30, 2950);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (30, 3381);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (31, 2460);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (32, 2550);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (33, 2430);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (34, 2500);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (35, 2275);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (36, 2547);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (37, 2390);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (38, 2800);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (39, 2450);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (40, 2330);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (41, 2400);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (42, 2640);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (43, 2845);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (44, 2560);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (45, 2250);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (46, 2360);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (47, 2580);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (48, 2870);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (49, 2520);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (50, 2380);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (51, 2470);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (52, 2310);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (53, 2840);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (54, 2627);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (55, 2970);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (56, 2900);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (57, 2860);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (58, 2940);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (59, 2300);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (60, 2290);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (61, 2350);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (62, 2260);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (63, 2110);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (64, 2830);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (65, 2160);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (66, 2990);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (67, 2240);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (68, 2980);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (69, 2070);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (70, 3800);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (70, 9300);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (71, 9880);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (72, 9960);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (73, 9290);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (74, 8791);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (74, 8800);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (75, 9660);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (76, 9255);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (77, 9800);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (78, 9470);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (79, 9200);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (80, 9840);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (81, 9070);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (82, 9900);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (83, 9420);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (84, 9940);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (85, 9890);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (86, 9500);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (87, 9000);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (88, 9450);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (89, 1785);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (89, 9220);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (90, 9550);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (91, 9667);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (92, 9970);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (93, 9690);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (94, 9150);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (95, 9750);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (95, 9770);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (95, 9771);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (95, 9772);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (96, 9270);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (97, 9280);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (98, 9340);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (99, 9570);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (100, 9920);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (101, 9080);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (102, 9160);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (103, 9680);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (104, 9990);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (105, 9090);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (106, 9820);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (107, 9500);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (108, 9810);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (109, 9400);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (110, 9860);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (111, 9700);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (112, 9600);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (113, 9170);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (114, 9980);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (115, 8630);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (115, 9520);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (116, 9830);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (117, 9100);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (118, 9190);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (119, 9140);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (120, 9250);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (121, 9185);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (122, 9230);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (123, 9260);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (124, 9790);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (125, 9240);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (126, 9060);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (127, 9620);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (128, 9870);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (129, 9630);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (130, 3200);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (131, 1790);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (132, 1730);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (133, 1650);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (134, 3130);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (135, 3460);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (136, 3060);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (137, 1547);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (138, 3360);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (139, 3190);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (140, 3370);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (141, 3290);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (142, 1700);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (143, 1620);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (144, 1570);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (145, 3450);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (146, 3380);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (147, 1755);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (148, 1850);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (149, 3150);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (150, 1500);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (150, 2980);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (151, 3020);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (152, 1540);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (153, 3320);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (154, 1560);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (155, 3220);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (156, 3040);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (157, 1910);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (158, 1880);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (159, 3140);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (160, 3470);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (161, 3070);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (162, 1950);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (163, 3400);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (164, 1750);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (165, 3000);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (166, 1770);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (167, 1630);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (168, 3350);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (169, 1840);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (170, 3210);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (171, 1830);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (171, 9870);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (172, 1860);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (173, 1785);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (174, 1745);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (175, 3050);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (176, 3090);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (177, 1670);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (178, 1760);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (179, 3110);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (180, 3270);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (181, 1640);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (182, 1600);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (183, 1820);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (184, 1740);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (185, 3080);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (186, 3390);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (187, 3300);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (188, 3120);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (189, 1800);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (190, 1780);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (191, 1970);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (192, 1930);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (193, 1980);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (194, 3440);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (195, 3570);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (196, 3665);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (197, 3580);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (198, 3740);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (199, 3950);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (200, 3840);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (201, 3960);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (202, 3590);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (203, 3650);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (204, 3600);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (205, 3890);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (206, 3545);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (207, 3945);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (208, 3930);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (209, 3500);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (210, 3940);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (211, 3870);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (212, 3540);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (213, 3717);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (214, 3550);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (215, 3730);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (216, 3530);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (217, 3640);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (218, 3720);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (219, 3620);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (220, 3970);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (221, 3920);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (222, 3560);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (223, 3680);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (224, 3630);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (225, 3850);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (225, 9320);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (226, 3670);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (227, 3990);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (228, 3900);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (228, 3910);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (229, 3770);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (230, 3800);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (231, 3980);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (232, 3700);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (233, 3790);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (233, 3791);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (233, 3792);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (233, 3793);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (233, 3798);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (234, 3830);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (235, 3520);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (236, 3690);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (237, 8690);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (238, 8570);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (239, 8850);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (240, 8580);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (241, 8730);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (242, 8370);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (243, 8450);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (244, 8200);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (244, 8310);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (244, 8380);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (244, 8000);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (245, 8340);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (246, 8540);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (247, 8420);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (248, 8720);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (249, 8660);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (250, 8600);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (251, 8470);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (252, 8530);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (253, 8950);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (254, 8830);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (255, 8650);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (256, 8480);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (257, 8770);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (258, 8870);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (259, 8490);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (260, 8300);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (261, 8680);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (262, 8670);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (263, 8610);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (264, 8500);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (265, 8520);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (266, 8920);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (267, 8880);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (268, 8860);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (269, 8810);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (270, 8647);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (271, 8930);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (272, 8957);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (273, 8760);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (274, 8430);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (275, 8890);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (276, 8620);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (277, 8020);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (278, 8780);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (279, 8400);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (280, 8460);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (281, 8740);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (282, 8970);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (283, 8800);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (284, 8755);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (285, 8587);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (286, 8840);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (287, 3390);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (287, 8700);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (288, 8820);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (289, 8630);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (290, 8640);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (291, 8790);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (292, 8940);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (293, 8560);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (294, 8710);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (295, 8750);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (296, 8900);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (296, 8902);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (296, 8904);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (296, 8906);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (296, 8908);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (297, 8210);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (298, 8980);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (299, 8377);
INSERT INTO POSTCODES (MUNICIPALITY_ID, POST_CODES)
VALUES (300, 8550);

insert into app_user(email, first_name, last_name, password, post_code, username, is_general_admin, date_created)

values ('lars@kdg.be', 'lars', 'willemsens', '$2a$10$18EoK.5JsBfwnm7.4MYmqu9kYQa1fqRf66ZjIKZS2dSHpvZJMuiSa', '2000',
        'lars', true, '2020-06-06 12:55:44');
-- password is 'lars'
