CREATE TABLE ACTION_POINT_IMAGE (
    ACTION_POINT_ID BIGINT NOT NULL,
    IMAGE VARCHAR(255),
    PRIMARY KEY (ACTION_POINT_ID, IMAGE)
);

CREATE TABLE ACTION_POINTS_LINKED_IDEAS (
    ACTION_POINT_ID BIGINT NOT NULL,
    IDEA_ID BIGINT NOT NULL,
    PRIMARY KEY (ACTION_POINT_ID, IDEA_ID) ON DELETE CASCADE
);

--done till here

CREATE TABLE ACTION_POINT (
    ID BIGINT NOT NULL IDENTITY(1,1),
    CREATED_DATE TIMESTAMP,
    DESCRIPTION VARCHAR(255),
    STATUS VARCHAR(255),
    TITLE VARCHAR(255),
    VIDEO VARCHAR(255),
    STANDARDACTION_ID BIGINT,
    YOUTH_COUNCIL_ID BIGINT,
    PRIMARY KEY (ID)
	);

CREATE TABLE ACTION_POINT_COMMENT (
    ID BIGINT NOT NULL IDENTITY(1,1),
    CONTENT VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    ACTION_POINT_ID BIGINT,
    USER_ID BIGINT,
    PRIMARY KEY (ID)
);

CREATE TABLE ACTION_POINT_LIKE (
    LIKED_DATE_TIME TIMESTAMP,
    USER_ID BIGINT NOT NULL,
    ACTION_POINT_ID BIGINT NOT NULL,
    PRIMARY KEY (ACTION_POINT_ID, USER_ID) ON DELETE CASCADE
);

CREATE TABLE ACTIVITY (
    ID BIGINT NOT NULL IDENTITY(1,1),
    DESCRIPTION VARCHAR(255),
    END_DATE DATE,
    NAME VARCHAR(255),
    START_DATE TIMESTAMP,
    YOUTH_COUNCIL_ID BIGINT,
    PRIMARY KEY (ID)
);

CREATE TABLE ANSWER (
  ID BIGINT IDENTITY(1,1),
  ANSWER VARCHAR(255),
  QUESTION_ID BIGINT,
  PRIMARY KEY (ID)
)

CREATE TABLE APP_USER (
  USER_ID BIGINT NOT NULL IDENTITY(1,1),
  DATE_CREATED TIMESTAMP,
  EMAIL VARCHAR(255),
  FIRST_NAME VARCHAR(255),
  IS_GENERAL_ADMIN VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255),
  PASSWORD VARCHAR(255),
  POST_CODE VARCHAR(255),
  USERNAME VARCHAR(255),
  PRIMARY KEY (USER_ID)
);

CREATE TABLE IDEA (
  ID BIGINT NOT NULL IDENTITY(1,1),
  CREATED_DATE TIMESTAMP,
  DESCRIPTION VARCHAR(255),
  AUTHOR_ID BIGINT,
  THEME_ID BIGINT,
  YOUTH_COUNCIL_ID BIGINT,
  PRIMARY KEY (ID)
);


CREATE TABLE IDEA_COMMENT(
    ID BIGINT NOT NULL IDENTITY(1,1),
    CONTENT VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    USER_ID BIGINT,
    IDEA_ID BIGINT,
    PRIMARY KEY (ID)
);


CREATE TABLE IDEA_IMAGE (
    ID BIGINT NOT NULL IDENTITY(1,1),
    IDEA_ID BIGINT,
    PRIMARY KEY (ID)
);

CREATE TABLE IDEA_LIKE (
    LIKED_DATE_TIME TIMESTAMP,
    IDEA_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    PRIMARY KEY (IDEA_ID, USER_ID) ON DELETE CASCADE
);

CREATE TABLE INFORMATIVE_PAGE_TEMPLATE (
    ID BIGINT NOT NULL IDENTITY(1,1),
    TITLE VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE INFORMATIVE_PAGE_TEMPLATE_SECTION (
    ID BIGINT NOT NULL IDENTITY(1,1),
    BODY VARCHAR(255),
    HEADER VARCHAR(255),
    TEMPLATE_ID BIGINT,
    PRIMARY KEY (ID)
);

CREATE TABLE MEMBERSHIP (
    DATE_JOINED TIMESTAMP,
    ROLE VARCHAR(255),
    USER_ID BIGINT NOT NULL,
    YOUTH_COUNCIL_ID BIGINT NOT NULL
);

CREATE TABLE MUNICIPALITY (
  ID BIGINT NOT NULL IDENTITY(1,1),
  NAME VARCHAR(255),
  PRIMARY KEY (ID)
);


CREATE TABLE NEWS_ITEM (
  ID BIGINT NOT NULL IDENTITY(1,1),
  CONTENT VARCHAR(255),
  CREATED_DATE TIMESTAMP,
  TITLE VARCHAR(255),
  AUTHOR_ID BIGINT,
  YOUTH_COUNCIL_ID BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE NEWS_ITEM_COMMENT (
  ID BIGINT NOT NULL IDENTITY(1,1),
  CONTENT VARCHAR(255),
  CREATED_DATE TIMESTAMP,
  USER_ID BIGINT,
  NEWS_ITEM_ID BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE NEWS_ITEM_LIKE (
  LIKED_DATE_TIME TIMESTAMP,
  USER_ID BIGINT NOT NULL,
  NEWS_ITEM_ID BIGINT NOT NULL,
  PRIMARY KEY (USER_ID, NEWS_ITEM_ID) ON DELETE CASCADE
);


CREATE TABLE POSTCODES (
  MUNICIPALITY_ID BIGINT NOT NULL,
  POST_CODES INT
);

CREATE TABLE QUESTION (
  ID BIGINT NOT NULL IDENTITY(1,1),
  QUESTION VARCHAR(255),
  QUESTIONNAIRE_ID BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE QUESTIONNAIRE (
  ID BIGINT NOT NULL IDENTITY(1,1),
  DATE_ADDED TIMESTAMP,
  DESCRIPTION VARCHAR(255),
  NAME VARCHAR(255),
  YOUTH_COUNCIL_ID BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE SECTION (
  ID BIGINT NOT NULL IDENTITY(1,1),
  BODY VARCHAR(500),
  HEADING VARCHAR(255),
  WEBPAGE_ID BIGINT,
  PRIMARY KEY (ID)
);

--done

CREATE TABLE SOCIAL_MEDIA_LINK (
  ID BIGINT NOT NULL IDENTITY(1,1),
  LINK VARCHAR(255),
  SOCIAL_MEDIA INT,
  YOUTH_COUNCIL_ID BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE STANDARD_ACTION (
  ID BIGINT NOT NULL IDENTITY(1,1),
  NAME VARCHAR(255),
  THEME_ID BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE STYLE (
  ID BIGINT NOT NULL IDENTITY(1,1),
  FONT VARCHAR(255),
  PRIMARY_COLOR VARCHAR(255),
  SECONDARY_COLOR VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE THEME (
  ID BIGINT NOT NULL IDENTITY(1,1),
  NAME VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE WEB_PAGE (
  ID BIGINT NOT NULL IDENTITY(1,1),
  ACTION_POINTS_ENABLED int NOT NULL DEFAULT 0,
  ACTIVITIES_ENABLED int NOT NULL DEFAULT 0,
  CALL_FOR_IDEAS_ENABLED int NOT NULL DEFAULT 0,
  CALL_TO_COMPLETE_QUESTIONNAIRE_ENABLED int NOT NULL DEFAULT 0,
  ELECTION_INFORMATION_ENABLED int NOT NULL DEFAULT 0,
  IS_HOMEPAGE int NOT NULL,
  NEWS_ITEMS_ENABLED int NOT NULL DEFAULT 0,
  TITLE VARCHAR(255),
  YOUTH_COUNCIL_ID BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE YOUTH_COUNCIL (
ID BIGINT NOT NULL IDENTITY(1,1),
NAME VARCHAR(255),
SLUG VARCHAR(255),
HOME_PAGE_ID BIGINT,
MUNICIPALITY_ID BIGINT,
QUESTIONNAIRE_ID BIGINT,
STYLE_ID BIGINT,
PRIMARY KEY (ID)
);

ALTER TABLE YOUTH_COUNCIL ADD CONSTRAINT UK_5ABF2S154W7LI3K571T0T7O7Y UNIQUE(SLUG);
ALTER TABLE APP_USER ADD CONSTRAINT UK_1J9D9A06I600GD43UU3KM82JW UNIQUE(EMAIL);
ALTER TABLE APP_USER ADD CONSTRAINT UK_3K4CPLVH82SRUEUTTFKWNYLQ0 UNIQUE(USERNAME);
ALTER TABLE MUNICIPALITY ADD CONSTRAINT UK_11HTXJ74B8C2D1P7FST9W3POP UNIQUE(NAME);
ALTER TABLE NEWS_ITEM_COMMENT ADD CONSTRAINT FKLGFDY4GJ7R2NQPPVO0XGB6KW2 FOREIGN KEY(NEWS_ITEM_ID) REFERENCES NEWS_ITEM(ID) ;
ALTER TABLE ACTIVITY ADD CONSTRAINT FKGF7O7RHRFLCDBUN2BNEQQNS9M FOREIGN KEY(YOUTH_COUNCIL_ID) REFERENCES YOUTH_COUNCIL(ID) ;
ALTER TABLE IDEA ADD CONSTRAINT FK4KUP2PCSW1VC1O4TLSSEW9E9E FOREIGN KEY(AUTHOR_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE ;
ALTER TABLE IDEA_COMMENT ADD CONSTRAINT FK57FCVUQ82F33BV8OKRSA2USQI FOREIGN KEY(USER_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE ;
ALTER TABLE ACTION_POINT ADD CONSTRAINT FKTII7O3BGNF3FM7M5VWXY8PNFD FOREIGN KEY(STANDARDACTION_ID) REFERENCES STANDARD_ACTION(ID) ON DELETE CASCADE ;
ALTER TABLE MEMBERSHIP ADD CONSTRAINT FKN2J6UUIDWVVIFKAUN5PE8OQKM FOREIGN KEY(USER_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE;
ALTER TABLE ACTION_POINT_LIKE ADD CONSTRAINT FK6GHKJULEYWB8JB73T8V0P8PY5 FOREIGN KEY(USER_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE ;
ALTER TABLE QUESTIONNAIRE ADD CONSTRAINT FKCRCIG8Q3DXVXFPGK556OG1IRA FOREIGN KEY(YOUTH_COUNCIL_ID) REFERENCES YOUTH_COUNCIL(ID) ON DELETE CASCADE ;
ALTER TABLE SOCIAL_MEDIA_LINK ADD CONSTRAINT FKRT727J2TQ2MSYUWU6U54MQ0LM FOREIGN KEY(YOUTH_COUNCIL_ID) REFERENCES YOUTH_COUNCIL(ID) ON DELETE CASCADE ;
ALTER TABLE NEWS_ITEM ADD CONSTRAINT FKE0VX8KWSV4UUD504H9SGTK422 FOREIGN KEY(AUTHOR_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE;
ALTER TABLE IDEA_LIKE ADD CONSTRAINT FKM36RP5N402GKV0DXI3SLBBIL3 FOREIGN KEY(USER_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE;
ALTER TABLE POSTCODES ADD CONSTRAINT FKRJP85LPRRIJOTIBIEP0SV2S2U FOREIGN KEY(MUNICIPALITY_ID) REFERENCES MUNICIPALITY(ID) ON DELETE CASCADE ;
ALTER TABLE IDEA_IMAGE ADD CONSTRAINT FKLX7BRU4PY1AP8C5214TKJV86O FOREIGN KEY(IDEA_ID) REFERENCES IDEA(ID) ON DELETE CASCADE;
ALTER TABLE ANSWER ADD CONSTRAINT FK8FRR4BCABMMEYYU60QT7IIBLO FOREIGN KEY(QUESTION_ID) REFERENCES QUESTION(ID) ON DELETE CASCADE ;
ALTER TABLE ACTION_POINT_COMMENT ADD CONSTRAINT FKKD3PYA7V1XVI32J1A5PPGFEV9 FOREIGN KEY(USER_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE ;
ALTER TABLE IDEA_COMMENT ADD CONSTRAINT FKIY0H5DC5E6KYI1DHBXDLWWFOW FOREIGN KEY(IDEA_ID) REFERENCES IDEA(ID) ON DELETE CASCADE;

ALTER TABLE WEB_PAGE ADD CONSTRAINT FKRT2D3L169SBPPQ4V8ERRNVIFW FOREIGN KEY(YOUTH_COUNCIL_ID) REFERENCES YOUTH_COUNCIL(ID)  ON DELETE CASCADE ;
ALTER TABLE IDEA_LIKE ADD CONSTRAINT FKSP1MO36VKL3Y5J3S6B6W89G8D FOREIGN KEY(IDEA_ID) REFERENCES IDEA(ID) ON DELETE CASCADE  ON DELETE CASCADE ;
ALTER TABLE NEWS_ITEM_LIKE ADD CONSTRAINT FKE8R97D9EOWGAXC9XX2EJ0QT89 FOREIGN KEY(USER_ID) REFERENCES APP_USER(USER_ID)  ON DELETE CASCADE ;
ALTER TABLE MEMBERSHIP ADD CONSTRAINT FKC85LEVCAFY9A0ST26Y2975U1R FOREIGN KEY(YOUTH_COUNCIL_ID) REFERENCES YOUTH_COUNCIL(ID)  ON DELETE CASCADE ;
ALTER TABLE IDEA ADD CONSTRAINT FK395GHF4SW02GBYKO4URD2TR3N FOREIGN KEY(THEME_ID) REFERENCES THEME(ID)  ON DELETE CASCADE ;
ALTER TABLE IDEA ADD CONSTRAINT FKIMLYSUMNUWIVLUJSSGDJNLJSN FOREIGN KEY(YOUTH_COUNCIL_ID) REFERENCES YOUTH_COUNCIL(ID)  ON DELETE CASCADE ;

ALTER TABLE NEWS_ITEM_LIKE ADD CONSTRAINT FKFWK1YVGP1YU3D2D4M6W5OSNYU FOREIGN KEY(NEWS_ITEM_ID) REFERENCES NEWS_ITEM(ID)  ON DELETE CASCADE ;
ALTER TABLE YOUTH_COUNCIL ADD CONSTRAINT FKKEOKC4ABDA1LEPHGUC6GCLSR8 FOREIGN KEY(QUESTIONNAIRE_ID) REFERENCES QUESTIONNAIRE(ID) ON DELETE CASCADE  ;
ALTER TABLE ACTION_POINT_LIKE ADD CONSTRAINT FK5N4KMDT3O35GV7USDST7J97G1 FOREIGN KEY(ACTION_POINT_ID) REFERENCES ACTION_POINT(ID)  ON DELETE CASCADE ;
ALTER TABLE NEWS_ITEM_COMMENT ADD CONSTRAINT FK8GXUBX8RQI990K14SN6V41GAQ FOREIGN KEY(USER_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE  ;
ALTER TABLE STANDARD_ACTION ADD CONSTRAINT FKBK0RIRISW5PIGGU8U74H8BIEQ FOREIGN KEY(THEME_ID) REFERENCES THEME(ID) ON DELETE CASCADE  ;
ALTER TABLE QUESTION ADD CONSTRAINT FK5A4P6BL440C9AMSQ08RS546WU FOREIGN KEY(QUESTIONNAIRE_ID) REFERENCES QUESTIONNAIRE(ID)  ON DELETE CASCADE ;
ALTER TABLE YOUTH_COUNCIL ADD CONSTRAINT FKP8Y3GUJ8MDTBDCHXEF7WT2QIV FOREIGN KEY(HOME_PAGE_ID) REFERENCES WEB_PAGE(ID) ON DELETE CASCADE  ;
ALTER TABLE YOUTH_COUNCIL ADD CONSTRAINT FK6T0UT3KJUKAW37X8XV58HDAIG FOREIGN KEY(STYLE_ID) REFERENCES STYLE(ID) ON DELETE CASCADE  ;
ALTER TABLE SECTION ADD CONSTRAINT FK25T7MPO3CU00N2SEPFILPYINN FOREIGN KEY(WEBPAGE_ID) REFERENCES WEB_PAGE(ID) ON DELETE CASCADE  ;
ALTER TABLE ACTION_POINT ADD CONSTRAINT FKP3OF679M1WO9I9FTMLJ8O9BUP FOREIGN KEY(YOUTH_COUNCIL_ID) REFERENCES YOUTH_COUNCIL(ID) ON DELETE CASCADE  ;
ALTER TABLE ACTION_POINT_COMMENT ADD CONSTRAINT FK3HA2VH5LP8FGIDQDHT1V5H33G FOREIGN KEY(ACTION_POINT_ID) REFERENCES ACTION_POINT(ID)  ON DELETE CASCADE ;
ALTER TABLE YOUTH_COUNCIL ADD CONSTRAINT FKQWULWYXPCCJP0FYTJO2AVHX6W FOREIGN KEY(MUNICIPALITY_ID) REFERENCES MUNICIPALITY(ID) ON DELETE CASCADE  ;
ALTER TABLE NEWS_ITEM ADD CONSTRAINT FKBSTT3AIXUB8FHK147KA4MYU9K FOREIGN KEY(YOUTH_COUNCIL_ID) REFERENCES YOUTH_COUNCIL(ID) ON DELETE CASCADE  ;
