### Get all ideas
GET http://antwerpyouthcouncil.localhost:8080/api/ideas



### Get idea with id 1
GET http://antwerpyouthcouncil.localhost:8080/api/ideas/2


### Get ideas of user - user not found
GET http://antwerpyouthcouncil.localhost:8080/api/users/1/ideas

### Post idea
//@no-cookie-jar
POST http://antwerpyouthcouncil.localhost:8080/api/ideas
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=000B7E5B802091B3100D1926CBC124EE
X-CSRF-TOKEN: 5b796959-9c6d-417c-affd-c9fb19aecbda

{
    "description": "New idea!" ,
    "images": ["okayimage.jpg", "goodimage.png", "greatimage.jpg"],
    "themeId": 1
}

### Post idea
//@no-cookie-jar
POST http://brusselsyouthcouncil.localhost:8080/api/ideas
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=000B7E5B802091B3100D1926CBC124EE
X-CSRF-TOKEN: 5b796959-9c6d-417c-affd-c9fb19aecbda

{
  "description": "New idea!" ,
  "images": ["okayimage.jpg", "goodimage.png", "greatimage.jpg"],
  "themeId": 1
}

### Like idea
//@no-cookie-jar
POST http://antwerpyouthcouncil.localhost:8080/api/ideas/2/likes
Accept: application/json
Content-Type: application/json
Content-Length: 0
Cookie: JSESSIONID=000B7E5B802091B3100D1926CBC124EE
X-CSRF-TOKEN: 5b796959-9c6d-417c-affd-c9fb19aecbda

### Post comment on idea
//@no-cookie-jar
POST http://antwerpyouthcouncil.localhost:8080/api/ideas/1/comments
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=000B7E5B802091B3100D1926CBC124EE
X-CSRF-TOKEN: 5b796959-9c6d-417c-affd-c9fb19aecbda

{
  "content" : "I agree, I don't think there are nearly enough study spaces at Karel de Grote."
}