### Get all action points
GET http://localhost:8080/api/youth-councils/1/action-points

### Get action point with id 1
GET http://localhost:8080/api/youth-councils/1/action-points/1

### Post idea
//@no-cookie-jar
POST http://localhost:8080/api/youth-councils/1/action-points
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=A3D99DD437B263A3AEA07A525032E1C4
X-CSRF-TOKEN: bf56506f-d442-4aa8-a583-95baa313e19b

{
  "statusName" :  "REALIZED",
  "title" : "New Action Point",
  "video" : "youtube.com/video",
  "description" : "Important issue!",
  "images" : ["picture1.jpg", "picture2.jpg"],
  "linkedIdeaIds" :  [1, 2],
  "standardActionId" :  2
}

### Post comment on action point
//@no-cookie-jar
POST http://localhost:8080/api/youth-councils/1/action-points/1/comments
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=A3D99DD437B263A3AEA07A525032E1C4
X-CSRF-TOKEN: bf56506f-d442-4aa8-a583-95baa313e19b

{
  "content" : "I am thrilled to see the Antwerp youth council taking action on improving study/education resources for young people in our city."
}