### Get all action points
GET http://antwerpyouthcouncil.localhost:8080/api/action-points

### Get action point with id 1
GET http://antwerpyouthcouncil.localhost:8080/api/action-points/1

### Post action point
//@no-cookie-jar
POST http://antwerpyouthcouncil.localhost:8080/api/action-points
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=000B7E5B802091B3100D1926CBC124EE
X-CSRF-TOKEN: 5b796959-9c6d-417c-affd-c9fb19aecbda

{
  "statusName" :  "REALIZED",
  "title" : "New Action Point",
  "video" : "youtube.com/video",
  "description" : "Important issue!",
  "images" : ["picture1.jpg", "picture2.jpg"],
  "linkedIdeaIds" :  [1, 2],
  "standardActionId" :  2
}

### Post comment on action point
//@no-cookie-jar
POST http://antwerpyouthcouncil.localhost:8080/api/action-points/1/comments
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=000B7E5B802091B3100D1926CBC124EE
X-CSRF-TOKEN: 5b796959-9c6d-417c-affd-c9fb19aecbda

{
  "content" : "I am thrilled to see the Antwerp youth council taking action on improving study/education resources for young people in our city."
}