@startuml YouthCouncilDesignClassDiagram

left to right direction

skinparam linetype ortho

package domain{
package account{

    class User {
    }

    class GeneralAdministrator{
    }

    abstract Account{
        - email : String
        - password : String
        - firstName : String
        - lastName : String
        - postCode : int
    }



}




package "Modules" {


    class IdeaModule{
    }

    class ActionPointModule{
    }

    class NewsItemModule{
    }

    class ActivityModule{
    }

    class CallForIdeasModule{
    }

    interface Module{
    }

    class QuestionnaireModule{
    }
    class FooterModule{

    }

    IdeaModule "1" --> "*" element::Idea : "ideas"
    ActionPointModule "1" --> "*" element::ActionPoint : "actionPoints"
    NewsItemModule "1" --> "*" element::NewsItem : "newsItems"
    ActivityModule "1" --> "*" element::Activity : "activities"
    CallForIdeasModule "1" --> "*" element::Idea : "callForIdeas"
    QuestionnaireModule "1" --> "*" element::Questionnaire : "questionnaires"
    FooterModule "1" --> "*" element::SocialMediaLink : "socialMediaLinks"


}
note left
    The modules are the building blocks of a website, they are the sections that we can enable or disable.
end note


package platform{
    interface Builder{
    }

    class WebPageBuilder{
    }

    class WebPage{
        - id : long
        - title : String
    }
    class Section{
        - header : String
        - body : String
        - image : String
    }

    class HashMap{

    }
    note left
        This is a hashmap that's inside WebPage
    end note
    enum Element{
        IDEAS
        ACTION_POINTS
        NEWS_ITEMS
        CALENDAR
        CALL_FOR_IDEAS
        QUESTIONNAIRE
        FOOTER
    }

    class YouthCouncil{
        - id : long
        - name : String
        - logo : String
    }

    class Municipality{
        - id : long
        - name : String
        - postCodes : List<Integer>
    }
    class Membership{
        - id : long
        - joinDate : LocalDateTime
        - role : Role
    }


    enum Role{
        MEMBER
        MODERATOR
        ADMINISTRATOR
    }
    package style{
    class Style{
        - primaryColor : Color
        - secondaryColor : Color
        - font : Font
    }
    enum Font{
        ARIAL
        TIMES_NEW_ROMAN
        COURIER_NEW
        CALIBRI
        COMIC_SANS_MS
    }

    enum Color{
        RED
        GREEN
        BLUE
        YELLOW
        BLACK
        WHITE
    }

    }

    package YouthCouncilItems{
        enum ActionPointStatus{
            BEFORE_ELECTION
            NOT_INCLUDED
            INCLUDED
            IN_PROGRESS
            REALIZED
        }
        enum SocialMedia{
            FACEBOOK
            TWITTER
            INSTAGRAM
            LINKEDIN
        }
        class SocialMediaLink{
            - socialMedia : SocialMedia
            - link : String
        }
        class ActionPoint{
            - id : long
            - status : ActionPointStatus
            - title : String
            - video : String
            - description : String
            - images : List<String>
            - dateAdded : LocalDateTime
            - likes : long
        }

        ActionPoint "1" --> "*" user::User : "followers"
        Idea  "*" --> "1" user::User : "author"


        class NewsItem{
            - id : long
            - title : String
            - content : String
            - image : String
        }

        class Activity{
            - id : long
            - startDateTime: LocalDateTime
            - endDateTime:  LocalDateTime
            - name : String
            - description : String
        }

        class Theme{
            - id : long
            - name : String
            - likes : long
        }
        class StandardAction{
            - id : long
            - theme : Theme
            - name : String
        }

        class Idea{
            - id : long
            - description : String
            - images : List<String>
            - dateAdded : LocalDateTime
            - likes : long
        }
        class Comment{
            - id : long
            - content : String
            - likes : long
            - dateAdded : LocalDateTime
            }
        Comment "1" --> "1" user::User : "author"

         package Questionnaire{
        class Questionnaire{
            - title : String
            - description : String
        }

        class QuestionnaireQuestion{
        }

        class Question{
            - questionText : String
        }

        class QuestionnaireQuestionResponse{
            - answer : String
        }

        class MultipleChoiceQuestion{
        }

        class MultipleChoiceQuestionResponse{
        }

        class Option{
            - optionText : String
        }



    }
}
}
}
package repository{
    interface JpaRepository{
    }
    interface YouthCouncilRepository{
        + existsById(id: long) : boolean
        + findYouthCouncilById(id: long) : YouthCouncil
    }
    interface IdeaRepository{
    }
    interface ModuleRepository{
    }
    interface ActionPointRepository{
        + findActionPointByYouthCouncilIdFilterByThemeId(youthCouncilId: long, themeId: long) : List<ActionPoint>
    }
    interface NewsItemRepository{
    }
    interface ActivityRepository{
    }
    interface QuestionnaireRepository{
    }
    interface WebPageRepository{
    }
    interface QuestionRepository{
    }
    interface UserRepository{
    }
    interface ThemeRepository{
    }
    interface StandardActionRepository{
    }

    service::UserServiceImpl --> UserRepository
    service::YouthCouncilServiceImpl --> YouthCouncilRepository
    service::IdeaServiceImpl --> IdeaRepository
    service::ActionPointServiceImpl --> ActionPointRepository
    service::NewsItemServiceImpl --> NewsItemRepository
    service::ActivityServiceImpl --> ActivityRepository
    service::ModuleServiceImpl --> ModuleRepository
    service::QuestionnaireServiceImpl --> QuestionnaireRepository
    service::WebPageServiceImpl --> WebPageRepository
    service::QuestionServiceImpl --> QuestionRepository
    service::ThemeServiceImpl --> ThemeRepository
    service::StandardActionServiceImpl --> StandardActionRepository


}
package controller{
            class UserController{

                    }

                    class QuestionnaireController{
                     + addQuestionToQuestionnaire(questionnaireId: long, question: Question)
                     + removeQuestionFromQuestionnaire(questionId: long)
                    }
                    class QuestionController{
                    }

                    class ActionPointController{
                        + getActionPointsByTheme(youthCouncilId: long, themeId: long): ResponseEntity<List<ActionPoint>>
                    }

                    class NewsItemController{
                    }
                    class ModuleController{
                    }

                    class ActivityController{
                    }

                    class IdeaController{
                        + submitIdea(newIdeaDto: NewIdeaDto): ResponseEntity<IdeaDto>
                    }

                    class WebPageController{
                    }
                    class ThemeController{
                    }
                    class StandardActionController{
                    }


            class YouthCouncilController{
            }
            QuestionnaireController ..> questionnaire::Questionnaire
            ActionPointController ..> actionPoint::ActionPoint
            NewsItemController ..> newsItem::NewsItem
            ActivityController ..> activity::Activity
            IdeaController ..> idea::Idea
            WebPageController ..> webPage::WebPage
            ThemeController ..> theme::Theme
            StandardActionController ..> standardAction::StandardAction
            YouthCouncilController ..> youthCouncil::YouthCouncil
            UserController ..> user::User
            QuestionController ..> question::Question
            ModuleController ..> module::Module

            package dto{
                class ActionPointDto{
                    - id : long
                    - status : Status
                    - title : String
                    - video : String
                    - description : String
                    - images : List<String>
                    - dateAdded : LocalDateTime
                    - likes : long
                    - comments : List<CommentDto>
                }
                class CommentDto{
                    - id : long
                    - content : String
                    - likes : long
                    - dateAdded : LocalDateTime
                    - authorName : String
                    - authorId : long
                }
                class UserDto{
                    id: long
                    firstName : String
                    lastName : String
                    email : String
                    postCode : int
                }

                class NewsItemDto{
                    - id : long
                    - title : String
                    - content : String
                    - image : String
                }

                class ActivityDto{
                    - id : long
                    - startTime : LocalDateTime
                    - endTime : LocalDateTime
                    - name : String
                    - description : String
                }
                class newActivityDto{
                    - startTime : LocalDateTime
                    - endTime : LocalDateTime
                    - name : String
                    - description : String
                }

                class ThemeDto{
                    - id: long
                    - name: String
                    - standardActions : List<StandardActionDto>
                }
                class StandardActionDto{
                    - id: long
                    - name: String
                }

                class IdeaDto{
                    - id: long
                    - description: String
                    - images: List<String>
                    - themeName: String
                    - authorName: String
                    - dateAdded: LocalDateTime
                    - likes: long
                    - comments: List<CommentDto>
                    - 
                }
                class NewIdeaDto{
                    - description: String
                    - images: List<String>
                    - themeId: long
                    - authorId: long
                }
                class QuestionnaireDto{
                    - id : long
                    - title : String
                    - description : String
                    - questions : List<QuestionDto>
                }
                class QuestionDto{
                    - id : long
                    - questionText : String
                    - questionType : QuestionType
                    - options : List<OptionDto>
                }
                class OptionDto{
                    - id : long
                    - optionText : String
                }
                class QuestionnaireQuestionResponseDto{
                    - id : long
                    - answer : String
                }
                class MultipleChoiceQuestionResponseDto{
                    - id : long
                    - answer : String
                }
                class YouthCouncilDto{
                    - id : long
                    - name : String
                    - description : String
                    - logo : String
                }
            }
}

package service{
        interface UserService{
            +findUserById(userId: long): User
        }

        interface QuestionnaireService{
        }
        interface QuestionService{
        }

        interface ActionPointService{
            + findActionPointByThemeId(youthCouncilId: long, themeId: long): List<ActionPoint>
            + findActionPointByYouthCouncilIdFilterByThemeId(youthCouncilId: long, themeId: long) : List<ActionPoint>
        }

        interface NewsItemService{
        }

        interface QuestionService{
        }

        interface ActivityService{
        }
        interface ModuleService{
        }

        interface IdeaService{
            + createIdea(idea: Idea): Idea
        }

        interface WebPageService{
        }

        interface YouthCouncilService{
            + getYouthCouncilById(youthCouncilId: long): YouthCouncil
        }

        class UserServiceImpl{
            +findUserById(userId: long): User
        }

        class QuestionnaireServiceImpl{
        }
        class QuestionServiceImpl{
        }

        class ActionPointServiceImpl{
            - youthCouncilRepository: YouthCouncilRepository
            + findActionPointByThemeId(youthCouncilId: long, themeId: long): List<ActionPoint>
            + findActionPointByYouthCouncilIdFilterByThemeId(youthCouncilId: long, themeId: long) : List<ActionPoint>
        }

        class NewsItemServiceImpl{
        }

        class ActivityServiceImpl{
        }
        class ModuleServiceImpl{
        }

        class IdeaServiceImpl{
            - youthCouncilRepository: YouthCouncilRepository
            - userRepository: UserRepository
            + createIdea(idea: Idea): Idea
        }

        class WebPageServiceImpl{
        }

        class YouthCouncilServiceImpl{
            + getYouthCouncilById(youthCouncilId: long): YouthCouncil
        }
        interface ThemeService{
        }
        class ThemeServiceImpl{
        }
        interface StandardActionService{
        }
        class StandardActionServiceImpl{
        }

        controller::UserController --> UserServiceImpl
        controller::QuestionnaireController --> QuestionnaireServiceImpl
        controller::QuestionController --> QuestionServiceImpl
        controller::ActionPointController --> ActionPointServiceImpl
        controller::NewsItemController --> NewsItemServiceImpl
        controller::ActivityController --> ActivityServiceImpl
        controller::ModuleController --> ModuleServiceImpl
        controller::IdeaController --> IdeaServiceImpl
        controller::WebPageController --> WebPageServiceImpl
        controller::YouthCouncilController --> YouthCouncilServiceImpl
        controller::ThemeController --> ThemeServiceImpl
        controller::StandardActionController --> StandardActionServiceImpl

        
        ActionPointServiceImpl ..> user::User
        ActionPointServiceImpl ..> actionPoint::ActionPoint
        IdeaServiceImpl ..> idea::Idea
        IdeaServiceImpl ..> youthCouncil::YouthCouncil
        UserServiceImpl ..> user::User
        YouthCouncilServiceImpl ..> youthCouncil::YouthCouncil
        ThemeServiceImpl ..> theme::Theme
        StandardActionServiceImpl ..> standardAction::StandardAction
        QuestionnaireServiceImpl ..> questionnaire::Questionnaire
        QuestionServiceImpl ..> question::Question
        NewsItemServiceImpl ..> newsItem::NewsItem
        ActivityServiceImpl ..> activity::Activity
        ModuleServiceImpl ..> module::Module
        WebPageServiceImpl ..> webPage::WebPage


}





    Account <|-- User
    YouthCouncil "*" --> "*" User
    (YouthCouncil, User) . Membership
    Account <|-- GeneralAdministrator





    Question <|-- MultipleChoiceQuestion

    MultipleChoiceQuestion "1" --> "2..*" Option
    MultipleChoiceQuestionResponse "*" --> "1" Option

    QuestionnaireQuestion "*" --> "1" Question
    QuestionnaireQuestion "*" --> "1" Questionnaire
    QuestionnaireQuestion "1" <-- "*" QuestionnaireQuestionResponse

    QuestionnaireQuestionResponse "*" --> "1" User

    ActionPointModule ..|> Module
    NewsItemModule ..|> Module
    ActivityModule ..|> Module
    QuestionnaireModule ..|> Module
    IdeaModule ..|> Module
    CallForIdeasModule ..|> Module
    FooterModule ..|> Module

    Municipality "1" <-- "1" YouthCouncil
    YouthCouncil "1"-->"1" Style
    YouthCouncil "1" --> "*" WebPage

    YouthCouncil "1" --> "*" ActionPoint
    YouthCouncil "1" --> "*" NewsItem
    YouthCouncil "1" --> "*" Activity
    YouthCouncil "1" --> "*" Idea
    YouthCouncil "1" --> "1" Questionnaire
    YouthCouncil "1" --> "*" SocialMediaLink


    ActionPoint "*" --> "1" Theme
    ActionPoint "1" --> "*" Idea : "linked idea"
    Idea "*" --> "1" Theme
    Theme "1" --> "*" StandardAction
    Idea "1" --> "*" Comment
    ActionPoint "1" --> "*" Comment



    WebPage "1" <-- "1" WebPageBuilder
    WebPageBuilder ..|> Builder
    WebPage "1" --> "1" HashMap
    HashMap "1" --> "*" Module : "value"
    HashMap "1" --> "*" Element : "key"
    WebPage "1" --> "*" Section


    UserServiceImpl ..|> UserService

    QuestionnaireServiceImpl ..|> QuestionnaireService
    ActionPointServiceImpl ..|> ActionPointService
    NewsItemServiceImpl ..|> NewsItemService
    ActivityServiceImpl ..|> ActivityService
    ModuleServiceImpl ..|> ModuleService
    IdeaServiceImpl ..|> IdeaService
    WebPageServiceImpl ..|> WebPageService
    YouthCouncilServiceImpl ..|> YouthCouncilService
    ThemeServiceImpl ..|> ThemeService
    StandardActionServiceImpl ..|> StandardActionService
    QuestionServiceImpl ..|> QuestionService

    ' all repositories extend jparepository
    UserRepository ..|> JpaRepository
    YouthCouncilRepository ..|> JpaRepository
    ActionPointRepository ..|> JpaRepository
    NewsItemRepository ..|> JpaRepository
    ActivityRepository ..|> JpaRepository
    ModuleRepository ..|> JpaRepository
    IdeaRepository ..|> JpaRepository
    WebPageRepository ..|> JpaRepository
    ThemeRepository ..|> JpaRepository
    StandardActionRepository ..|> JpaRepository
    QuestionRepository ..|> JpaRepository











@enduml