@startuml

Actor User
participant ":IdeaController" as IdeaController <<Controller>>
participant ":IdeaService" as IdeaService <<Service>>
participant ":IdeaRepository" as IdeaRepository <<Repository>>
participant ":Idea" as Idea <<Entity>>


activate User
User -> IdeaController : submitIdea(long userId, String Description, Image image, Theme theme)

activate IdeaController
create Idea
IdeaController -->> Idea : <<create>>
IdeaController -> IdeaService : submitIdea(Idea idea)
activate IdeaService
alt IdeaService.checkIdeaLength(idea) == true


alt OK
IdeaService -> IdeaRepository : save(Idea idea)
activate IdeaRepository
deactivate IdeaRepository
IdeaService -->> IdeaController : HttpStatus.OK
IdeaController -> User : HttpStatus.OK
else SQLException
IdeaService -> IdeaRepository : save(Idea idea)
activate IdeaRepository
IdeaRepository -> IdeaService : SQLException()
deactivate IdeaRepository
IdeaService -->> IdeaController : HttpStatus.BAD_REQUEST
IdeaController -> User : HttpStatus.BAD_REQUEST
end
else IdeaService.checkIdeaLength(idea) == false
IdeaService -->> IdeaController : HttpStatus.BAD_REQUEST
IdeaController -> User : HttpStatus.BAD_REQUEST
end

@enduml
