
@startuml

Actor WebUser
participant ":IdeaController" as IdeaController <<Controller>>
participant ":IdeaService" as IdeaService <<Service>>
participant ":IdeaRepository" as IdeaRepository <<Repository>>
participant "responseEntity:ResponseEntity<IdeaDto>" as ResponseEntity <<Entity>>
participant "newIdeaDto:NewIdeaDto" as NewIdeaDto <<Entity>>
participant "idea:Idea" as Idea <<Entity>>
participant "ideaDto:IdeaDto" as IdeaDto <<Entity>>
participant ":UserRepository" as UserRepository <<Repository>>
participant ":YouthCouncilRepository" as YouthCouncilRepository <<Repository>>
participant "youthCouncil:YouthCouncil" as YouthCouncil <<Entity>>


activate WebUser
WebUser -> IdeaController : submitIdea(youthCouncilId: long, newIdeaDto: NewIdeaDto): ResponseEntity<IdeaDto>
note left
POST /api/youth-council/{youthCouncilId}/ideas HTTP/1.1
        body: {
        {
        "description": "Idea description",
        "images": [
        "IFAOIUFDUOI88uuuu",
        "wadadadsaAA9990",
        ],
        "themeId": 1,
        "authorId": 5
        }
        }
end note
activate IdeaController
IdeaController -> IdeaService : createIdea(idea: Idea): Idea
activate IdeaService
IdeaService -> YouthCouncilRepository : youthCouncil = findById(youthCouncilId: long): YouthCouncil
activate YouthCouncilRepository
deactivate YouthCouncilRepository
IdeaService -> UserRepository : user = findById(authorId: long): User
activate UserRepository
deactivate UserRepository
alt user == null OR youthCouncil == null
create ResponseEntity
IdeaController --> ResponseEntity: <<create>> (HttpStatus.NOT_FOUND)
IdeaController --> WebUser : responseEntity: ResponseEntity<>
note left
HTTP/1.1 404 Not Found
end note
else
IdeaService -> IdeaRepository : save(idea: Idea): Idea
activate IdeaRepository
deactivate IdeaRepository
create IdeaDto
IdeaService --> IdeaDto: <<create>> (idea: Idea)
IdeaService -> YouthCouncil : addIdea(idea: Idea)
activate YouthCouncil
deactivate YouthCouncil
deactivate IdeaService
create ResponseEntity
IdeaController --> ResponseEntity: <<create>> (ideaDto: IdeaDto, HttpStatus.CREATED)
IdeaController --> WebUser : responseEntity: ResponseEntity<>
deactivate IdeaController
note left
HTTP/1.1 200 OK
Content-Type: application/json
        {
        "id": 1,
        "description": "Idea description",
        "images": [
        "IFAOIUFDUOI88uuuu",
        "wadadadsaAA9990",
        ],
        "themeId": 1,
        "authorId": 5
        }
    end note
end

@enduml
